apiVersion: v1
kind: ServiceAccount
metadata:
  name: chappaai
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chappaai
rules:
  # Chappaai Custom Resources
  - apiGroups:
      - chappaai.dev
    resources:
      - "*"
    verbs:
      - "*"
  # Ability to write events about our resources
  - apiGroups:
      - events.k8s.io
    resources:
      - events
    verbs:
      - create
  # Ability to manage secrets with OAuth tokens
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - get
      - create
      - delete
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chappaai
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chappaai
subjects:
  - kind: ServiceAccount
    name: chappaai
