apiVersion: v1
kind: ServiceAccount
metadata:
  name: chappaai
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chappaai
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - list
      - get
      - create
      - delete
      - patch
      - update
      - watch
  - apiGroups:
      - chappaai.dev
    resources:
      - oauthapis
      - oauthconnections
    verbs:
      - list
      - get
      - create
      - delete
      - patch
      - update
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: chappaai
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: chappaai
subjects:
  - kind: ServiceAccount
    name: chappaai
    namespace: default
