apiVersion: chappaai.dev/v1
kind: OAuthApi
metadata:
  name: discord
spec:
  auth:
    oAuth2:
      authorizationUrl: "/oauth2/authorize"
      tokenUrl: "/oauth2/token"
      authorizationParams:
        - key: responseType
          value: code
        - key: grantType
          value: authorization_code
  http:
    baseUrl: "https://discord.com/api/"
    authorizationHeaderPrefix: Bearer
    headers:
      - key: Accept
        value: application/json
      - key: User-Agent
        value: stargate
---
apiVersion: chappaai.dev/v1
kind: OAuthConnection
metadata:
  name: discord
spec:
  api: discord
  scopes:
    - "identify"
    - "email"
  credentials:
    secretRef:
      #namespace: "current"
      name: "oauth-connection-discord"
      idKey: "clientId"
      secretKey: "clientSecret"
---
apiVersion: v1
kind: Secret
metadata:
  name: oauth-connection-discord
stringData:
  clientId: ""
  clientSecret: ""
