kind: OAuthApi
apiVersion: chappaai.dev/v1
metadata:
  name: youtube
spec:
  auth:
    oAuth2:
      authorizationUrl: "https://accounts.google.com/o/oauth2/v2/auth"
      tokenUrl: "https://www.googleapis.com/oauth2/v4/token"
      authorizationParams:
        - key: prompt
          value: consent
        - key: access_type
          value: offline
        - key: response_type
          value: code
      tokenParams:
        grantType: authorization_code
  http:
    baseUrl: "https://www.googleapis.com/youtube/v3/"
    authorizationHeaderPrefix: Bearer
    headers:
      - key: Accept
        value: application/json
      - key: User-Agent
        value: stargate
