name: release-operator

on:
  push:
    branches:
      - "main"
    paths:
      - ".github/workflows/release-operator.yaml"
      - "operator/**"

jobs:
  build-container-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v3
        with:
          context: operator
          platforms: linux/amd64
          tags: ghcr.io/rawkode/chappaai/operator:main
          push: true
